apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-ingress"
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host:
      http:
        paths:
          - backend:
              serviceName: {{ .Chart.Name }}
              servicePort: 80
            path: /healthcheck
          - backend:
              serviceName: {{ .Chart.Name }}
              servicePort: 80
            path: /get_results
